apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: n8n-secret
type: Opaque
stringData:
  DB_TYPE: postgresdb
  # TODO: change to azure database for postgresql
  DB_POSTGRESDB_HOST: psql-aoai-kc-axpg-dev-comm-01.postgres.database.azure.com
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: n8n
  DB_POSTGRESDB_USER: postgresadmdev
  DB_POSTGRESDB_PASSWORD: dbPassword1!
  DB_POSTGRESDB_SSL_ENABLED: "true"
  N8N_PROTOCOL: http
  N8N_PORT: "5678"
  # self hosting: https://docs.n8n.io/hosting/configuration/configuration-examples/isolation/
  N8N_DIAGNOSTICS_ENABLED: "false"
  N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
  N8N_TEMPLATES_ENABLED: "false"
  EXTERNAL_FRONTEND_HOOKS_URLS: ""
  N8N_DIAGNOSTICS_CONFIG_FRONTEND: ""
  N8N_DIAGNOSTICS_CONFIG_BACKEND: ""
  # Locale
  N8N_DEFAULT_LOCALE: ko
  # Learn more: https://docs.n8n.io/hosting/configuration/task-runners/
  N8N_RUNNERS_ENABLED: "true"
  # settings
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  # https://docs.n8n.io/hosting/logging-monitoring/monitoring/
  N8N_METRICS: "true"
  QUEUE_HEALTH_CHECK_ACTIVE: "true"
